server.port=8080

# Koneksi Supabase
spring.datasource.url=jdbc:postgresql://db.sckmayvflfdgpxgznvfb.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=greenmarketkece1

# Matikan ddl-auto agar tidak menimpa skema manual Anda
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Untuk debugging (melihat query yang dijalankan)
spring.jpa.show-sql=true